#!/bin/bash
#
echo "Choose instance:"
echo "1. Windows XP"
echo "2. Windows 7"

read num
dis=`ps -ef | grep -c kvm`
let dis=$dis-3

case $num in
		1)
				echo "use rdesktop to connecting to Windows XP"
				rdesktop localhost:3389 -x 0x80 -z -P -a 24 -u virtio \
						-g 1300x680 -r sound:local -k en-us -K -T 'Virtio@KVM' \
						-r disk:Public=/home/havanna/Public -clipboard &
				;;
		2)
				echo "connecting to Windows 7"
				rdesktop localhost:3389 -x 0x80 -z -P -u virtio \
						-g 1024x600 -r sound:local -k en-us -K -T '@Virtio' \
						-r disk:Public=/home/havanna/Public -clipboard &
				;;
esac

exit 0
